spring:
  datasource:
    url: jdbc:postgresql://localhost:5429/task_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: public

logging:
  level:
    org.hibernate:
      type.descriptor.sql.BasicBinder: TRACE
      SQL: DEBUG